# Generated by Django 3.2.7 on 2021-09-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210907_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porjects',
            name='subheader',
        ),
    ]
