# Generated by Django 3.2.7 on 2021-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_porjects_subheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='porjects',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
